---
# yamllint disable rule:line-length
# yamllint disable rule:comments-indentation
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "bevo2"
  namespace: "bevo2"
spec:
  baseDomain: "cars2.lab"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.14.17-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDd7Jj5iFCWv9IHJK9H+2O3lyPs36moAxeAUiHvzRS3uzqGxxB33BnTRBNDKsoDFSGJX0J4bd5b+XyCPdhFOfvn/xhmAcm6d8GALS+139e8d+No8h2QgZy0OVJFp844k4nmz4wew5/+X9DN40ZURYerekbVc58hw1+rTu0uM2jQ0cE2QmEf3qGKHx9UJW8t6IsMzwnrikBH30sYqn2NcBE+/c8JzlLc3PvvenlY0iQkpukI1A5E9GGMR9OS/q+w6FH85zvSgUatOV7Q5lg45QUF+V77DrfX5+niI+NK1g70pRvD8481SAdXrHPB5vK4vQEmJ4pz83IKYHVuPzRnjzYKv1jV33oReyyMqyk44Rsfkxl4i5SJ9z7q/EVmTjvurzD6ofi3Dg0+PL18eTcjuPFdCxSCUFsnr5N9CRHCxHRQpxoZTD7sYD4jDGNygawLvhxcvgKGBZzP53NRCzRFOMFmZsLPLQRaNOsgKRPAohmrn5l8+1xG5ltVauOwAFlKUxk="
  clusters:
    - clusterName: "bevo2"
      networkType: "OVNKubernetes"
      extraManifests:
        searchPaths:
          - ../../ztp-policies/bevo/extra-manifest
      installConfigOverrides: "{\"capabilities\":{\"baselineCapabilitySet\": \"None\", \"additionalEnabledCapabilities\": [ \"marketplace\", \"NodeTuning\" ] }}"
      cpuPartitioningMode: AllNodes
      clusterLabels:
        common-du-414: true
        group-dellr750-vse6: ""
      clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
        #- cidr: fd01::/48
        #  hostPrefix: 64
      machineNetwork:
        - cidr: 192.168.38.128/26
        #- cidr: 2600:52:7:300::0/64
      serviceNetwork:
        - 172.30.0.0/16
        #- fd02::/112
      additionalNTPSources:
        - clock.cars2.lab
        #- clock-v6.cars2.lab
      # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
      # crTemplates:
      # KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
      # proxy:
      # httpProxy: http://cars2-client.infra.cars2.lab:3128
      # httpsProxy: http://cars2-client.infra.cars2.lab:3128
      # noProxy: ".cars2.lab,2600:52:7:300::0/64,fd02::/112,fd01::/48,2600:52:7:300::177,2600:52:7:300::179,2600:52:7:300::180,2600:52:7:300::181"
      nodes:
        - hostName: "r750-2.bevo2.cars2.lab"
          role: "master"
          # Optionally; This can be used to configure desired BIOS setting on a host:
          # biosConfigRef:
          # filePath: "example-hw.profile"
          bmcAddress: "idrac-virtualmedia://192.168.38.204/redfish/v1/Systems/System.Embedded.1"
          bmcCredentialsName:
            name: "r750-2-bmc-creds-secret"
          bootMACAddress: "e4:3d:1a:dd:b8:20"
          # Use UEFISecureBoot to enable secure boot
          bootMode: "UEFI"
          rootDeviceHints:
            deviceName: "/dev/disk/by-path/pci-0000:65:00.0-scsi-0:2:0:0"
          nodeNetwork:
            interfaces:
              - name: ens2f0
                macAddress: "b4:96:91:a5:04:ac"
              - name: ens2f1
                macAddress: "b4:96:91:a5:04:ad"
              - name: ens2f2
                macAddress: "b4:96:91:a5:04:ae"
              - name: ens2f3
                macAddress: "b4:96:91:a5:04:af"
              - name: ens5f0
                macAddress: "50:7c:6f:1f:b3:58"
              - name: ens5f1
                macAddress: "50:7c:6f:1f:b3:59"
              - name: ens5f2
                macAddress: "50:7c:6f:1f:b3:5a"
              - name: ens5f3
                macAddress: "50:7c:6f:1f:b3:5b"
              - name: eno12399np0
                macAddress: "e4:3d:1a:dd:b8:20"
              - name: eno12409np1
                macAddress: "e4:3d:1a:dd:b8:21"
              - name: eno12419np2
                macAddress: "e4:3d:1a:dd:b8:22"
              - name: eno12429np3
                macAddress: "e4:3d:1a:dd:b8:23"
            config:
              interfaces:
                - name: eno12399np0
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: "192.168.38.151"
                        prefix-length: 26
                    dhcp: false
                  #ipv6:
                  #  enabled: true
                  #  address:
                  #    - ip: "2600:52:7:300::151"
                  #      prefix-length: 64
                  #  autoconf: false
                  #  dhcp: false
                - name: eno12409np1
                  type: ethernet
                  state: down
                - name: eno12419np2
                  type: ethernet
                  state: down
                - name: eno12429np3
                  type: ethernet
                  state: down
                - name: ens2f0
                  type: ethernet
                  state: up
                - name: ens2f1
                  type: ethernet
                  state: down
                - name: ens2f2
                  type: ethernet
                  state: down
                - name: ens2f3
                  type: ethernet
                  state: down
                - name: ens5f0
                  type: ethernet
                  state: up
                - name: ens5f1
                  type: ethernet
                  state: down
                - name: ens5f2
                  type: ethernet
                  state: down
                - name: ens5f3
                  type: ethernet
                  state: down
              dns-resolver:
                config:
                  server:
                    - 192.168.38.12
                    #- 2600:52:7:38::12
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-address: 192.168.38.129
                    next-hop-interface: eno12399np0
                  #- destination: ::/0
                  #  next-hop-address: 2600:52:7:300::1
                  #  next-hop-interface: eno12399np0
