---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
 - puffin-siteconfig.yaml

resources:
 - github.com/redhat-partner-solutions/vse-ocp-bases/base/ztp/site-config?ref=main

patches:
 - target:
    kind: Secret
   patch: |-
     - op: replace
       path: /metadata/name
       value: 'puffin-bmc-creds-secret'
     - op: replace
       path: /metadata/namespace
       value: 'puffin-wpc-test'
     - op: replace
       path: /data/username
       value: 'cm9vdA=='
     - op: replace
       path: /data/password
       value: 'Y2FsdmluCg=='
 - target:
    kind: SealedSecret
   # yamllint disable rule:line-length
   patch: |-
     - op: replace
       path: /metadata/name
       value: 'assisted-deployment-pull-secret'
     - op: replace
       path: /metadata/namespace
       value: 'puffin-wpc-test'
     - op: replace
       path: /spec/encryptedData/.dockerconfigjson
       value: 'AgBzIsqwb+/XDUw3A3PWj3d1NUD+0Rv+4x/81xFkieozv0iBfjyt9xACIdAuntgg39aWVAaOx5l9+46TQHsulIRbSscFabSFIec2USZ0byjrLTnqyysxCSFwsC2r8PkFVHIw9eGNooOGn4NgBZ0tEdGu/l9p81bw0/6avi/PMVfAkcuV2Fe1yq0YZ3o+eHIrcvOUv0xKdbA5iwxttOpF/9jRxxsHNHdr8wzC62J3MxL9dqTj8t1mZxsL9W2SM7FfvC0TOIPX6dq+HhjrNNU0eGszJt+f54XcMIEzMgHaNT0m/Y1ahGw3YbvMgzXStE9DV7jHABfa+CXEGRs5Qqa53vH9OhR1nyj9EyXw6vhaRliUGw+hFr436V+sfFi6MEBWOQ4WpzXLRaw7PoHPnHBz5dGT0u4mZHjR7w0IJCyZYIl6fh7twqWXxEVaPerbX9ronR2/vAr6jTa1fIhz1EBMPLVxrcuKOKf+j95WnsvPcjDH7NzphSLsnU73ddTjBtpfhx+zhy8XlGC+CM+yxEz3NOQdIYlZYV1oEaA0qXRA66pgMqpSIREd4zOEZrce6jiJVXpCcI498fQ2AcQmuzsNtmJxVbmbNflLyqi2w7qYNecBaDPOrPPUUfQRaniR01ceURQdwH7D6ddDOmUBSPghiQPA1auE1Dmla/BHnsfibgIthE8qBMrFA3PR4wX1MYTUteW1CiZ7z5XWRqBPolR+p7V4LHEOz8LxvlO05WRalOyvZxSyyDxDMXnixc89MNKNF94zCB3OiV3ypVcIowjcKPhFmOkVpCpSyIUrCvOo5Nh4W0pvIYO++FRV2qblLqPwG9ML3L3lQkoSNR1H7T3kWwOmuIivSoA3zSGssXd+hdmLjTi1Nr0aZWwi8mfSrFosY+7xGnAImXfU3lTXLR/SydgpAXQcR8Go/tCc9HqIn/wRXg0tl4c1raqzCVg2EAYEWWgr2llXoI8oaleTgHE1glDWUVngd/LJeCfl6ZpYLIjfn+w2mYWkFlWbEPY07rSkVtYmt7OUOUiw2HFGO0Y+yrYmcOgR5tI5EeWINyQnLKdFEDdb0hS9ImWvGHCH7xj1qdIrG8irhstYQx/4nGiYA6Nyu5b0G/ftWHEUaWmNAoWJre1Uh5zmY03zoRVLyF/nnJ+wKUM5lxx7148qV8jo+oQqer53SKDEc4jM8KvkOCVoAm4cGInYoqh3VA/LkxFndjKXL0S5U89u4YDhripvrGy0w3DXwOeKWsRBcoN6nZvlzfZXM10aPfCb41FKZ6DgPY7MvX/fUlnXP6LFj7/6ZSDh+ckgul6UEJLorT+jdbMae6XuyHNVJh13SgQ0qwGx2X3X/juRuiz+exq1YHVlzxUcI7Yxhl/guFOaM08MHvE26wdP7GSucQJ0Y/EZgsXt6ea/xSlNNKp9Xm4AXsEMplSgy/AiZoFRAt4CnGN8V53NK7pKeFfg70D0Me2ei9CqI+Nfg12wPYCukIwoG1P2vDO7jHO6yRrovO1mNsb7FIHm7merrZdlnVbdSDy4vR9L2UTlcAzcRJcuyGvfULN6675Fuy4NQIVp6cgJznScXQFuS4HNUxIC5ZOj/nLyNrnz6leixrH4oRZKgFWWgwr/Isw+gGsMld1Vzk88KdemYOyje4gtkcL/PaQ7sck5iaN89CyCzY4EsIstfXpg+wy7W3K4HEva25ZTslgJCFznHW7JoqKQrbIgD3J33DG+H5534XrFQ66S6V8oAC8dRP/doKwS/BmNpFSEFdSAooCXxw74KIR7+ZIXUgN2iNl5MibY9xs0Ku0mx+wrtdPtE8e0K0ewY/5AHCPdMo7OdVJ3eRoZe0ib3F1xlcpVfCi4ja6vtiNeO9BYh8iwFX9Mckk52kJIXVStBpoeFJv2lW+UP4YHLI0o8ESpN+Z6XaLQjeKtFOcFoJ6zTFkqBDk6/JSAosEKO7CYQ9tMvaf64DYikh8wSPyZ0k2mpjsvjS16HhatYZGypBfck7vrZQGayx1ogAzeWgM9wiVARhDI1JxzyJZagQ85wtWKZ9dpYbAf3MNHfF7qsbwt/lhTRKDXO+4wY/d16l4SV5HxF1gxRYYs1ZnWSL7axT2fF1Q89lwWLyhFM5La7JQ+tjtq1LjcNhIzDm2H7pYd1EP2XBk/SVpwq9B9h8Ikf2SDQybYm3Unl+qUEJrSm6KbeiQACefMpf96WAR4S3L5lE2t3JrTaNneAx3M185sLeT2r+ojvg3wD3zY5Dx3Xu6Ds8di/jbKu6WkfIWlEYAIxwWtWKfVEqBqFKlV/XFphrx0hI72/EhVp+hWVYFxEwtmiPKlTEXvdcqloa8nklx6Q4ggeK2nBaP/rifAdnJtQVtXD6XmwRtz2aT445n0XqvtoLb+QR7EMceOgJpgtUguvqraQc2UVTWrLXLlLIhIm90QmdwVwaz3wFAyqAsHawlcBSma+m5hnN2nLvNMhxGBzK7MSC9qz/KfZjMicPaqDye8jNWcdNNv4V7a5+zukddZCcQ3Nyg0DAfwWtTStHT5rJdfu05w9nOT7XSyU0mcJF7/6vGgZstsXu8jmRKGS+YjTnGnleODQFISHHJ4bgkOUDRMehHp3vYpEsvh6gNaV8B3ia492Dni574z384IL7PaKRVIaCJC2dojv6ucjowWqE7zYxnyF8Tm8PrvBnfR90FZzOCceqa3EUkPiIDCCrOwvYaISjeD8L6b+1qFydLyJvJo4II6Fa8xWP0+Q1byBrar35s5fZk4ID9n3RWF7IM6qG0gyBA7eZJ+W6QbSgM/rJ0Ou++grhjwdD8CwpHRX5a06AGVyeaDQxIMJKYO0aJRE6p/vPM9es8S9uE4483uz7Np/xr8BVCiKSG52t/Up/kGbvpwAWwUQD636CjvNhPrlo8gCO4BIxMSzHOTn2mZxE+YBcKEigIqSNZR8eYVTKCQ4HXLx1igJ04CSKPpxxY4cCIXnT2+terbvR46U+A1kWy/YXxULrJJyd9OavwkZ/K2xXbw2TIMVcp0ul/PSwpgfgfeAgjQjL7e1BhE3VOsgz/S57epqDRJBPSqTGT6soyHKN6rST6+AITR2hNpdTH2C+rxeQ80IyyM8Xw+8o0IWNtxxHOZ62adk4TyRCyUvDV2QsAROzas7EX0WL5oHM7Rmm+BpHUN76ol832ykqm9nzityRtQ98FGqQyXtz+hJ7W3Jq1BR7reMfv2LFBfag5HJETkOxMuPgE019VykXhcAv2yk0axfoT3PKOJlK527PAlsayXuPqQSS2e7cYTLoRH8NZWLr/OfddM5NyXUCqd31hIS1w6VyfALXlfaO8bOxbmtqDO9JNq/wE3SLK42AePZjJ/XbeevZxQxsVUpbd2bCmbPSai30LL24EYGa/rXZRBckWZimQmDYdpgY8L+IEy6dG4NpthM5wBAZI9H43fF6nc60bTU/Zq6Lwjl7p2qhu1b0uAng3VGnBJVZX0J2TKFr8kqi51Rn+WecM8aIpY5DVBmRV2PvdxQ9/hVRL42Qi2pBMnVejF14e0b5QXnRI0y2SFAg206TnWgAMfpKmDboTilK+4fwFt5ZvRzRER2j3t1PWuRxP0/CnJC2I895yfHBPMJyiA0e3mfOMUvaeO3FOfAATQaQ1T4eeedZX1pjkU9/nSqndwk+12f060WLsqb7sBQaFRXaUYzpnIJO07KXFnS4zE/B80WyknsewmDPpy8qG//hx0017TaRZbYtBLzAhJDnTWJRbhMAel7oPhakKuFvKwET5IEzIlguTEIBEB8niIKfuLMn9WzzeGbVq9EdNXiPaHMMwbaGZDQhDqsfsH7cmQQRfDDIJf/oT69TktPVRXLhkN38mbq7kG2hCtu7JfCrHsxv6XdOJwzqtsXitKCL4nPjdkXmQqvGvful41omO15nVNEM2YP7Kz6SPBsqgtFA7NhhzeBvVfF2MPLVDY/J5uaQ+xHZ3mnFekROXaX9Vx8y7M5Tje5t6wUEILbE07r12YCC9TEKCPZATgsqakN2FE5TbuRWzTic9+wTfC9R7BAITNW1hBJ5e3fjPhFkPjzIr3RxNUj7rMGixj443EAUvbVfyezSxbVNoH1hh76EMCQWatQNuoFb+3RSgnhvg6Q4OiY7nvB4wH95Km5OSxi0Z/j+almInNDcamQr0NrFZLIZ67De0UNbQBB40tZdPgz1WBnXaX/GI79Vm1SsBkB74qf6HKJ5jsTTjAYRIaIVj9wBE3INYgqCrGUsDHf9huxL46Dvl2ABn7R2BgISbS92jmRbrF+c3fBa0fj1xGknzHoDsmCRn1QT5fhpiacGKfilbzj0WcEuxr6cN6ZQy7h8h1yPp5tupwTizQHa2MrOVKvOVKKbBFxl8ex4bv45LdXXQvKEaIprlQjh/PBgtJgODNzwdDEWMyaskYKOsnsHI='
     - op: replace
       path: /spec/encryptedData/type
     - op: replace
       path: /spec/template/metadata/name
       value: 'puffin-bmc-creds-secret'
     - op: replace
       path: /spec/template/metadata/namespace
       value: 'puffin-wpc-test'
