---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - core-components-appset.yaml
  # - clusters-appset.yaml
  # - worker-nodes-appset.yaml
  - ztp-clusters-appset.yaml
  - ztp-policies-appset.yaml
